rats-tls: add sev attester and verifier
inclavare-containers/inclavare-containers pull request #1498
Opened 2021-11-25 02:40 UTC by haosanzi

2021-11-25 06:43 UTC, jialez0 commented on rats-tls/src/attesters/sev/ttrpc/src/lib.rs
> +                        return Some(Box::new(wrap_command));
`return` is no need.

2021-11-25 06:43 UTC, jialez0 commented on rats-tls/src/attesters/sev/ttrpc/src/lib.rs
> +    let c = Client::connect(&addr[..]).context(format!("failed to connect {}", addr))?;
Just `&addr` is enough, no need to use `&addr[..]`.

2021-11-25 09:39 UTC, jiazhang0 requested changes

2021-11-25 09:39 UTC, jiazhang0 commented on rats-tls/cmake/CompilerOptions.cmake
> +# Normal, occlum, and sev mode
Change to `Normal, occlum and sev modes`.

2021-11-25 12:09 UTC, jiazhang0 requested changes

2021-11-25 12:09 UTC, jiazhang0 commented on rats-tls/src/attesters/sev/collect_evidence.c
> +	uint32_t evidence_size = retrieve_attestation_evidence_size(guest_handle);
Plz add the error check. E.g, what happens if AEB is not started?

2021-11-25 12:09 UTC, jiazhang0 commented on rats-tls/src/attesters/sev/collect_evidence.c
> +	RTLS_DEBUG("Succeed to generate the sev evidence!\n");
s/generate/retrieve/

2021-11-25 12:09 UTC, jiazhang0 commented on rats-tls/src/attesters/sev/collect_evidence.c
> +
Add a check:
```C
if (evidence_size != sizeof(sev_evidence)) {
  // error handling
}
```

2021-11-25 12:09 UTC, jiazhang0 commented on rats-tls/src/attesters/sev/collect_evidence.c
> +	sev_report->report_len = sizeof(sev_evidence);
change to `sev_report->report_len = evidence_size;`.

2021-11-25 12:09 UTC, jiazhang0 commented on rats-tls/src/attesters/sev/collect_evidence.c
> +extern sev_evidence *retrieve_attestation_evidence(uint32_t guest_handle, uint32_t evidence_size);
rename the type name to sev_evidence_t.

2021-11-26 01:52 UTC, jiazhang0 requested changes

2021-11-26 01:52 UTC, jiazhang0 commented on rats-tls/src/core/cpu.c
> +		RTLS_ERR("rdmsr: pread error\n");
Change to `RTLS_ERR("failed to read msr %#x\n", reg);`

2021-11-30 10:51 UTC, liangzhou121 commented on rats-tls/src/attesters/sev/ttrpc/src/lib.rs
> +}
I think the value can be returned directly, like
fn default_ctx() -> ttrpc::context::Context {
    ttrpc::context::with_timeout(0)
}

2021-11-30 10:58 UTC, liangzhou121 commented on rats-tls/src/attesters/sev/ttrpc/src/lib.rs
> +    let agent_client = connect().context("connect");
Maybe you can change the following snippet codes like this:
let res = connect().context("connect")
    .map_err(|e| {
	    error!("failed to retrieve evidence size from aeb service {:?}", e);
	    0
	})
	.and_then(|agent_client| {
	    let res = agent_client.retrieve_attestation_evidence_size(default_ctx(), &req)
		    .map_err(|e| {
			    error!("failed to retrieve evidence size from aeb service {:?}", e);
			    0
			})
			.and_then(|res| {res.evidence_size})
		OK(res)
	})
	.unwrap();

2021-12-02 12:37 UTC, jiazhang0 requested changes

2021-12-02 12:37 UTC, jiazhang0 commented on rats-tls/README.md
> +If you want to run SEV instances, please type the following command.
s/command/commands/

2021-12-02 12:37 UTC, jiazhang0 commented on rats-tls/README.md
> +  - Start the [attestation evidence broker](../attestation-evidence-broker/README.md) service in host.
sev attester may run in client side, so it is not appropriate to document the steps in "Run RATS TLS server".

2021-12-08 01:49 UTC, YangLiang3 approved these changes

2021-12-08 06:44 UTC, zhiminghufighting approved these changes

2021-12-30 03:26 UTC, jiazhang0 requested changes

2021-12-30 03:26 UTC, jiazhang0 commented on rats-tls/README.md
> +If you want to run SEV instances, please type the following command.
Please fix this issue.

2021-12-30 03:26 UTC, jiazhang0 commented on rats-tls/README.md
> +  - Start the [attestation evidence broker](../attestation-evidence-broker/README.md) service in host.
Once you move the patches to your AEB repo, then update these info.

2022-01-04 13:53 UTC, jiazhang0 commented on rats-tls/README.md
> +If you want to run SEV instances, please type the following commands.
change to `SEV(-ES)`.

2022-01-04 13:56 UTC, jiazhang0 requested changes

2022-01-04 13:56 UTC, jiazhang0 commented on rats-tls/README.md
> +- software capability:
remove this line.

2022-01-04 13:56 UTC, jiazhang0 commented on rats-tls/README.md
> +  - [Kernel supports to get guest firmware handle in guest](https://github.com/haosanzi/attestation-evidence-broker/blob/master/hack/0001-KVM-X86-Introduce-KVM_HC_VM_HANDLE-hypercall.patch).
s/supports/support/

2022-01-04 13:56 UTC, jiazhang0 commented on rats-tls/README.md
> +    - [Implement SEV_GET_REPORT ioctl command in ccp driver](https://github.com/haosanzi/attestation-evidence-broker/blob/master/hack/0003-crypto-ccp-Implement-SEV_GET_REPORT-ioctl-command.patch)
I suggest you create a README under the hack directory to talk about above words, and then refer to it here.

2022-02-23 07:47 UTC, haosanzi commented
I Will resubmitted to https://github.com/inclavare-containers/rats-tls.

2022-03-04 11:21 UTC, haosanzi commented
Resubmitted to https://github.com/inclavare-containers/rats-tls/pull/61.

2022-03-04 11:21 UTC, closed without merging